import React from 'react';
import { Document, Page, Text, View, StyleSheet, Image, Font } from '@react-pdf/renderer';

// Register standard fonts
// Note: In some environments you might need to register fonts explicitly if they aren't available.
// For simplicity, we use Helvetica (built-in).

const styles = StyleSheet.create({
    page: {
        flexDirection: 'column',
        backgroundColor: '#FFFFFF',
        padding: 40,
        fontFamily: 'Helvetica',
    },
    header: {
        marginBottom: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#EEEEEE',
        paddingBottom: 20,
    },
    brandName: {
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 5,
        color: '#111827',
    },
    reportTitle: {
        fontSize: 16,
        color: '#4B5563',
        marginBottom: 5,
    },
    meta: {
        fontSize: 10,
        color: '#6B7280',
        marginBottom: 3,
    },
    logo: {
        width: 60,
        height: 60,
        objectFit: 'contain',
        marginBottom: 10,
    },
    section: {
        margin: 10,
        padding: 10,
        flexGrow: 1,
    },
    statRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 10,
        paddingBottom: 5,
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
    },
    statLabel: {
        fontSize: 12,
        color: '#374151',
    },
    statValue: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#111827',
    },
    totalSection: {
        marginTop: 20,
        paddingTop: 10,
        borderTopWidth: 2,
        borderTopColor: '#000',
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 40,
        right: 40,
        textAlign: 'center',
        fontSize: 10,
        color: '#9CA3AF',
    },
});

interface EndOfDayProps {
    brandName: string;
    logoUrl?: string;
    date: string;
    generatedBy: string;
    stats: {
        totalSales: number;
        totalTips: number;
        transactionCount: number;
        averageOrderValue: number;
    };
    paymentMethods: { method: string; total: number }[];
}

export const EndOfDayPDF = ({ brandName, logoUrl, date, generatedBy, stats, paymentMethods }: EndOfDayProps) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <View style={styles.header}>
                {logoUrl && (
                    /* eslint-disable-next-line jsx-a11y/alt-text */
                    <Image
                        src={logoUrl}
                        style={styles.logo}
                    />
                )}
                <Text style={styles.brandName}>{brandName}</Text>
                <Text style={styles.reportTitle}>End of Day Report</Text>
                <Text style={styles.meta}>Date: {date}</Text>
                <Text style={styles.meta}>Generated by: {generatedBy}</Text>
            </View>

            <View style={styles.section}>
                <Text style={{ fontSize: 14, fontWeight: 'bold', marginBottom: 15 }}>Sales Summary</Text>

                <View style={styles.statRow}>
                    <Text style={styles.statLabel}>Total Sales (Gross)</Text>
                    <Text style={styles.statValue}>${stats.totalSales.toFixed(2)}</Text>
                </View>
                <View style={styles.statRow}>
                    <Text style={styles.statLabel}>Total Tips</Text>
                    <Text style={styles.statValue}>${stats.totalTips.toFixed(2)}</Text>
                </View>
                <View style={styles.statRow}>
                    <Text style={styles.statLabel}>Transaction Count</Text>
                    <Text style={styles.statValue}>{stats.transactionCount}</Text>
                </View>
                <View style={styles.statRow}>
                    <Text style={styles.statLabel}>Average Order Value</Text>
                    <Text style={styles.statValue}>${stats.averageOrderValue.toFixed(2)}</Text>
                </View>

                <View style={styles.totalSection}>
                    <View style={styles.statRow}>
                        <Text style={{ ...styles.statLabel, fontSize: 16 }}>Net Revenue</Text>
                        <Text style={{ ...styles.statValue, fontSize: 18 }}>${stats.totalSales.toFixed(2)}</Text>
                    </View>
                </View>
            </View>

            <View style={styles.section}>
                <Text style={{ fontSize: 14, fontWeight: 'bold', marginBottom: 15 }}>Payment Breakdown</Text>
                {paymentMethods.length === 0 && <Text style={{ fontSize: 12, color: '#666' }}>No data available</Text>}
                {paymentMethods.map((pm, i) => (
                    <View key={i} style={styles.statRow}>
                        <Text style={styles.statLabel}>{pm.method}</Text>
                        <Text style={styles.statValue}>${pm.total.toFixed(2)}</Text>
                    </View>
                ))}
            </View>

            <View style={styles.footer}>
                <Text>Generated via PortalPay Terminal • {new Date().toISOString()}</Text>
            </View>
        </Page>
    </Document>
);
